### ISSUE TITLE
choria req does not expand missing optional input parameters before validation

### ISSUE THREAD

**Issue by optiz0r** [choria-io/go-choria#699] opened 2019-09-25 10:28 UTC
Current behaviour when an optional input parameter is missing is to raise an error. 
```
± /usr/sbin/choria req puppet_env update_all
Discovering nodes .... 1

1 / 1    0s [====================================================================] 100%

puppetserver.local         Request Aborted
    Validation failed: validation failed for input 'force': is not a boolean

Finished processing 1 / 1 hosts in 55.176388ms
```

Expected behaviour is the request should go through as if the request were given with the input parameter at its default value:

```
± /usr/sbin/choria req puppet_env update_all force=false
Discovering nodes .... 1

1 / 1    0s [====================================================================] 100%

puppetserver.local
       Added: []
      Failed: []
     Removed: []
   Unchanged: ["qa", "production"]
     Updated: []

Finished processing 1 / 1 hosts in 751.033024ms
```

Relevant extract of DDL is: 
```json
{
      "action": "update_all",
      "input": {
        "force": {
          "prompt": "Force",
          "description": "Forces update of modules even if no changes were detected (can be slow)",
          "type": "boolean",
          "default": false,
          "optional": true,
          "validation": "",
          "maxlength": 0,
          "list": null
        }
      }
}
```

**Comment by ripienaar** [comment] 2019-09-25 15:51
I tried reproducing this with the following json:

```json
 "prefix": {
   "prompt": "Add Prefix",
   "description": "Prefix",
   "type": "boolean",
   "default": false,
   "optional": false
 },
```

And in an external I do:

```
external.Infof("%#v", string(request.Data))
```

where `request.Data` is the raw JSON received:

```
{"agent":"helloworld","component":"server","identity":"dev1.devco.net","level":"info","msg":"\"{\\\"message\\\":\\\"hello\\\",\\\"prefix\\\":false}\"","subsystem":"agents","time":"2019-09-25T17:49:24+02:00"}
```

This from: `choria req helloworld ping message=hello`

**Comment by ripienaar** [comment] 2019-09-25 15:56
Also added some test coverage for this scenario: https://github.com/choria-io/mcorpc-agent-provider/pull/123

**Comment by ripienaar** [comment] 2019-10-24 17:11
going to close this, cant reproduce give us a shout if its still a problem

**Closed** 2019-10-24 17:11 UTC
Labels: bug
